### ISSUE TITLE
Bug in selftest

### ISSUE THREAD

**Issue by jinningwang** [CURENT/andes#487]
**Describe the bug**
Command ``andes st`` run into AttributeError, and a full message is excerpted in the last.

**To Reproduce**
In a terminal, run ``andes st`` with the current development version.
I've reinstall in development mode by ``pip install -e .`` in the ANDES root path.

**Expected behavior**
Run self tests.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Darwin (Mac OS)
 - ANDES version: 1.8.10.post16+g596662e5

**pip packages (please paste the output from `pip list`)**

```bash
Package                       Version                 Editable project location
----------------------------- ----------------------- ---------------------------------------
alabaster                     0.7.12
andes                         1.8.10.post16+g596662e5 /Users/jinningwang/Documents/work/andes
anyio                         3.5.0
appnope                       0.1.3
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
astroid                       2.11.3
asttokens                     2.0.5
attrs                         21.4.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
beautifulsoup4                4.11.1
bleach                        5.0.0
bokeh                         2.4.3
Brotli                        1.0.9
brotlipy                      0.7.0
certifi                       2022.9.24
cffi                          1.15.0
cfgv                          3.3.1
chardet                       4.0.0
charset-normalizer            2.0.12
click                         8.1.3
click-completion              0.5.0
click-log                     0.3.2
cloudpickle                   2.1.0
codecov                       2.1.11
colorama                      0.4.4
coloredlogs                   15.0.1
coverage                      6.3.2
cryptography                  36.0.2
cssselect2                    0.7.0
cvxopt                        1.3.0
cycler                        0.11.0
cytoolz                       0.12.0
dask                          2022.9.0
debugpy                       1.6.0
decorator                     5.1.1
defusedxml                    0.7.1
dill                          0.3.4
distlib                       0.3.4
distributed                   2022.9.0
docutils                      0.17.1
entrypoints                   0.4
et-xmlfile                    1.0.1
executing                     0.8.3
fastjsonschema                2.15.3
filelock                      3.6.0
flake8                        4.0.1
flit_core                     3.7.1
fonttools                     4.33.3
fsspec                        2022.8.2
gitdb                         4.0.9
GitPython                     3.1.27
gmpy2                         2.1.2
greenlet                      1.1.2
gurobipy                      9.5.1
HeapDict                      1.0.1
hmmlearn                      0.2.7
html5lib                      1.1
humanfriendly                 10.0
identify                      2.5.0
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.3
importlib-resources           5.7.1
iniconfig                     1.1.1
ipykernel                     6.13.0
ipyparallel                   8.2.1
ipython                       8.2.0
ipython-genutils              0.2.0
ipywidgets                    7.7.0
isort                         5.10.1
jedi                          0.18.1
Jinja2                        3.0.3
joblib                        1.1.0
json5                         0.9.5
jsonschema                    4.4.0
jupyter                       1.0.0
jupyter-cache                 0.4.3
jupyter-client                7.3.0
jupyter-console               6.4.3
jupyter-core                  4.9.2
jupyter-server                1.16.0
jupyter-server-mathjax        0.2.5
jupyter-sphinx                0.3.2
jupyterlab                    3.4.3
jupyterlab-pygments           0.2.2
jupyterlab-server             2.14.0
jupyterlab-widgets            1.1.0
kiwisolver                    1.4.2
kvxopt                        1.3.0.0
lazy-object-proxy             1.7.1
libsass                       0.22.0
llvmlite                      0.36.0
locket                        1.0.0
lz4                           4.0.0
markdown-it-py                1.1.0
MarkupSafe                    2.1.1
matplotlib                    3.5.1
matplotlib-inline             0.1.3
matpower                      7.1.0.2.1.4
mccabe                        0.6.1
mdit-py-plugins               0.2.8
metakernel                    0.29.0
mistune                       0.8.4
mpmath                        1.2.1
msgpack                       1.0.4
multiprocess                  0.70.12.2
munkres                       1.1.4
myst-nb                       0.13.2
myst-parser                   0.15.2
nbclassic                     0.3.7
nbclient                      0.5.13
nbconvert                     6.4.5
nbdime                        3.1.1
nbformat                      5.3.0
nest-asyncio                  1.5.5
networkx                      2.8
nodeenv                       1.6.0
notebook                      6.4.11
notebook-shim                 0.1.0
numba                         0.53.1
numpy                         1.22.3
numpydoc                      1.2.1
oct2py                        5.5.1
octave-kernel                 0.34.2
openpyxl                      3.0.9
packaging                     21.3
pandapower                    2.8.0
pandas                        1.4.2
pandocfilters                 1.5.0
parso                         0.8.3
partd                         1.3.0
pathos                        0.2.8
patsy                         0.5.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.1.0
pip                           22.0.4
platformdirs                  2.5.1
pluggy                        1.0.0
portalocker                   2.4.0
pox                           0.3.0
ppft                          1.6.6.4
pre-commit                    2.18.1
prometheus-client             0.14.1
prompt-toolkit                3.0.29
psutil                        5.9.4
ptyprocess                    0.7.0
pure-eval                     0.2.2
py                            1.11.0
pycodestyle                   2.8.0
pycparser                     2.21
pydata-sphinx-theme           0.8.1
pydyf                         0.6.0
pyflakes                      2.4.0
Pygments                      2.12.0
pylint                        2.13.5
pyOpenSSL                     22.0.0
pyparsing                     3.0.8
pyphen                        0.14.0
pyrsistent                    0.18.1
PySocks                       1.7.1
pytest                        7.0.1
python-dateutil               2.8.2
pytz                          2022.1
PyYAML                        6.0
pyzmq                         22.3.0
requests                      2.27.1
SciencePlots                  2.0.1
scikit-learn                  1.0.2
scipy                         1.8.0
seaborn                       0.11.2
Send2Trash                    1.8.0
setuptools                    62.1.0
shellingham                   1.4.0
six                           1.16.0
sklearn                       0.0
smmap                         3.0.5
sniffio                       1.2.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.1
Sphinx                        4.5.0
sphinx-copybutton             0.5.0
sphinx-panels                 0.6.0
sphinx-simplepdf              1.6.0
sphinx-togglebutton           0.3.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    1.4.36
stack-data                    0.2.0
statsmodels                   0.13.2
swifter                       1.3.4
sympy                         1.8
tblib                         1.7.0
terminado                     0.13.3
testpath                      0.6.0
texttable                     1.6.4
threadpoolctl                 3.1.0
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
tornado                       6.1
tqdm                          4.64.0
traitlets                     5.1.1
typing_extensions             4.2.0
ukkonen                       1.0.1
unicodedata2                  14.0.0
urllib3                       1.26.9
virtualenv                    20.14.1
wcwidth                       0.2.5
weasyprint                    59.0
webencodings                  0.5.1
websocket-client              1.3.2
wheel                         0.37.1
widgetsnbextension            3.6.0
wrapt                         1.14.1
xlrd                          2.0.1
XlsxWriter                    3.0.3
zict                          2.2.0
zipp                          3.8.0
zopfli                        0.2.2
```

**Additional context**
Full error message is excerpted below:
```bash
andes) jinningwang@jwmba-3 andes % andes st

    _           _         | Version 1.8.10.post16+g596662e5
   /_\  _ _  __| |___ ___ | Python 3.9.12 on Darwin, 10/20/2023 04:10:03 PM
  / _ \| ' \/ _` / -_|_-< | 
 /_/ \_\_||_\__,_\___/__/ | This program comes with ABSOLUTELY NO WARRANTY.

Traceback (most recent call last):
  File "/Users/jinningwang/Documents/work/mambaforge/envs/andes/bin/andes", line 33, in <module>
    sys.exit(load_entry_point('andes', 'console_scripts', 'andes')())
  File "/Users/jinningwang/Documents/work/andes/andes/cli.py", line 238, in main
    return func(cli=True, **vars(args))
  File "/Users/jinningwang/Documents/work/andes/andes/main.py", line 818, in selftest
    for t in test_class._tests:
  File "/Users/jinningwang/Documents/work/mambaforge/envs/andes/lib/python3.9/unittest/loader.py", line 32, in __getattr__
    return super(_FailedTest, self).__getattr__(name)
AttributeError: 'super' object has no attribute '__getattr__'
```

**Comment by jinningwang** [comment]
I tried to fix this error but has no clue for now. Do you have any suggestion?

**Comment by cuihantao** [comment]
It could be that pytest is broken. You can try updating pytest to 7.4 and retry

**Comment by jinningwang** [comment]
The bug is addressed after deleting andes environment and creating a new one.

Before creating a new environment, updating ``pytest`` version to 7.4 does not solve the trouble. Still not sure what's the real reason.
Complete message is excerpted below, here the ``pytest`` version is not listed out but turned out to be 7.0.1.
```bash
(andes) jinningwang@jwmba-3 andes % andes

    _           _         | Version 1.8.10.post16+g596662e5
   /_\  _ _  __| |___ ___ | Python 3.11.6 on Darwin, 10/20/2023 10:47:17 PM
  / _ \| ' \/ _` / -_|_-< | 
 /_/ \_\_||_\__,_\___/__/ | This program comes with ABSOLUTELY NO WARRANTY.

usage: andes [-h] [-v {1,10,20,30,40}] {run,plot,doc,misc,prepare,prep,selftest,st,demo} ...

positional arguments:
  {run,plot,doc,misc,prepare,prep,selftest,st,demo}
                        [run] run simulation routine; [plot] plot results; [doc] quick documentation; [misc] misc.
                        functions; [prepare] prepare the numerical code; [selftest] run self test;

options:
  -h, --help            show this help message and exit
  -v {1,10,20,30,40}, --verbose {1,10,20,30,40}
                        Verbosity level in 10-DEBUG, 20-INFO, 30-WARNING, or 40-ERROR.
(andes) jinningwang@jwmba-3 andes % pip list
Package             Version                 Editable project location
------------------- ----------------------- ---------------------------------------
andes               1.8.10.post16+g596662e5 /Users/jinningwang/Documents/work/andes
chardet             5.2.0
coloredlogs         15.0.1
contourpy           1.1.1
cycler              0.12.1
dill                0.3.7
et-xmlfile          1.1.0
fonttools           4.43.1
humanfriendly       10.0
importlib-resources 6.1.0
kiwisolver          1.4.5
kvxopt              1.3.2.0
llvmlite            0.41.1
matplotlib          3.8.0
mpmath              1.3.0
multiprocess        0.70.15
numba               0.58.1
numpy               1.26.1
openpyxl            3.1.2
packaging           23.2
pandas              2.1.1
pathos              0.3.1
Pillow              10.1.0
pip                 23.3
pox                 0.3.3
ppft                1.7.6.7
psutil              5.9.6
pyparsing           3.1.1
python-dateutil     2.8.2
pytz                2023.3.post1
PyYAML              6.0.1
scipy               1.11.3
setuptools          68.2.2
six                 1.16.0
sympy               1.12
texttable           1.7.0
tqdm                4.66.1
tzdata              2023.3
wheel               0.41.2
XlsxWriter          3.1.9
zipp                3.17.0
```

**Comment by cuihantao** [comment]
Something was broken but I'm glad that the issue is resolved.
